import bcrypt from 'bcryptjs';

const data = {
	users: [
		{
			name: 'dannydev',
			email: 'admin@example.com',
			password: bcrypt.hashSync('1234', 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: 'Puma',
				logo: '/images/logo1.png',
				description: 'best seller',
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: 'John',
			email: 'user@example.com',
			password: bcrypt.hashSync('1234', 8),
			isAdmin: false,
		},
	],

	products: [
		{
			name: 'sharwama',
			slug: 'sharwama',
			category: 'bakery',
			image: '/img/image52.png',
			price: 120,
			countInStock: 10,
			description: 'Hot bakery',
			rating: 3,
			numReviews: 56,
		},
		{
			name: 'picsa',
			slug: 'picsa',
			category: 'bakery',
			image: '/img/image50.png',
			price: 150,
			countInStock: 50,
			description: 'Hot bakery',
			rating: 3,
			numReviews: 56,
		},
		{
			name: 'Mayonase',
			slug: 'mayonase',
			category: 'cupboard',
			image: '/img/image59.png',
			price: 900,
			countInStock: 50,
			description: 'Food cupboard',
			rating: 3,
			numReviews: 56,
		},
		{
			name: 'apple',
			slug: 'apple',
			category: 'fresh',
			image: '/img/image45.png',
			price: 200,
			countInStock: 0,
			description: 'Fresh fruit',
			rating: 2,
			numReviews: 56,
		},
		{
			name: 'Ready meat',
			slug: 'ready-meat',
			category: 'cuisnes',
			image: '/img/image55.png',
			price: 120,
			countInStock: 0,
			description: 'Ready meat',
			rating: 4,
			numReviews: 566,
		},
		{
			name: 'Mamador',
			slug: 'mamador',
			category: 'cupboard',
			image: '/img/image42.png',
			price: 120,
			countInStock: 30,
			description: 'Food cupboard',
			rating: 1,
			numReviews: 26,
		},
		{
			name: 'Beef sharwama',
			slug: 'beef-sharwama',
			category: 'bakery',
			image: '/img/image49.png',
			price: 820,
			countInStock: 0,
			description: 'Hot bakery',
			rating: 5,
			numReviews: 516,
		},
		{
			name: 'Oreo',
			slug: 'oreo',
			category: 'cupboard',
			image: '/img/image58.png',
			price: 620,
			countInStock: 10,
			description: 'food cupboard',
			rating: 2,
			numReviews: 42,
		},
		{
			name: 'wheat',
			slug: 'wheat',
			category: 'fresh',
			image: '/img/image54.png',
			price: 520,
			countInStock: 0,
			description: 'Fresh food',
			rating: 5,
			numReviews: 56,
		},
		{
			name: 'Chicken pie ',
			slug: 'chicken-pie',
			category: 'bakery',
			image: '/img/image51.png',
			price: 120,
			countInStock: 0,
			description: 'Hot bakery',
			rating: 4,
			numReviews: 26,
		},
		{
			name: 'Pomegrante blueberry',
			slug: 'pomegrante-blueberry',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_1.jpg',
			price: 500,
			countInStock: 10,
			description:
				'Pomegrante blueberry pure fruit flavored juice enriched  with no sugar added.',
			rating: 3,
			numReviews: 556,
			brand: 'Pomegrante',
		},
		{
			name: 'Welchs',
			slug: 'welchs',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_2.jpg',
			price: 150,
			countInStock: 50,
			description:
				'Welchs Freeze dried Apple slices flavor juice Nothing adde, 100% fruit. ',
			rating: 4,
			numReviews: 56,

			brand: 'Pomegrante',
		},
		{
			name: 'Essentials',
			slug: 'essentials',
			category: 'cupboard',
			image: '/img/hotdeal/hotdeal_3.jpg',
			price: 900,
			countInStock: 50,
			description:
				'Emegency Essentials freeze-dried cinnamon apple slices. BePrepared.com product.',
			rating: 3,
			numReviews: 56,

			brand: 'BePrepared.com',
		},
		{
			name: 'Dried Apricots',
			slug: 'dried-apricots',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_4.jpg',
			price: 200,
			countInStock: 6,
			description:
				'Dried Apricots an organic traditions product a source of fiber, sustainably grown and harvested, unsulfered and naturally dried.',
			rating: 5,
			numReviews: 556,
			brand: 'organic',
		},
		{
			name: 'Berry almondmilk',
			slug: 'berry-almondmilk',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_5.jpg',
			price: 120,
			countInStock: 0,
			description:
				'Berry flavored almondmilk blend with 6 juice & other natural flavors.',
			rating: 2,
			numReviews: 566,
			brand: 'pure friut',
		},
		{
			name: 'Medley',
			slug: 'medley',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_6.jpg',
			price: 120,
			countInStock: 0,
			description:
				'Organic fruit Medley is dried fruit reinvented. A combination of Apricots + Plums + Figs fruit deliciously juicy.  ',
			rating: 1,
			numReviews: 26,
			brand: 'Organic',
		},
		{
			name: 'Blue machine',
			slug: 'blue-machine',
			category: 'hotdeals',
			image: '/img/hotdeal/hotdeal_7.jpg',
			price: 820,
			countInStock: 0,
			description:
				'Boosted smoothe blue machine a blend of 4 juices with added ingredients & other natural flavors 100% juice smoothe.',
			rating: 5,
			numReviews: 516,
			brand: 'Boosted smoothe',
		},
	],
};

export default data;
